### ISSUE TITLE
Prelude support

### ISSUE THREAD

**Issue by leonardlorenz** [leonardlorenz/leaf#1]
# TODO:

- [x] read in environment variables LEAFPATH and current directory
- [x] read files in prelude directory from $(pwd)/prelude
- [x] read files in prelude directory from LEAFPATH env variable
- [x] detect all files in a directory ending in .lf
- [x] call crate::parser::Parser.tokenize() on them
- [x] crate::parser::Parser.type_check(func) on the functions returned by the tokenize method
